### ISSUE TITLE
新版本打不开什么情况~

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [cjinhuo/blazwitcher#31]
更新到新版本后就打不开了~ 我用的是谷歌122内核

**Comment by liuhuapiaoyuan** [comment]
🙍‍♀️ 重度使用者，忽然就打开不了~~~~我用的360浏览器

**Comment by cjinhuo** [comment]
> 更新到新版本后就打不开了~ 我用的是谷歌122内核

你看看 background 有什么报错吗
<img width="455" alt="image" src="https://github.com/user-attachments/assets/d6578eb4-23b6-4ff6-a249-767d70e7bd0e">

**Comment by cjinhuo** [comment]
是 mac 还是 window

**Comment by liuhuapiaoyuan** [comment]
win11  最惨的就是 backgroud 无响应，打不开

**Comment by liuhuapiaoyuan** [comment]
我一会自己编译 dev 看一下是啥原因，我感觉是谷歌内核版本问题

**Comment by cjinhuo** [comment]
> 我一会自己编译 dev 看一下是啥原因，我感觉是谷歌内核版本问题

嗯 好，这次加了标签页面的 group 分组获取和展示，还加了 host 的搜索，有啥问题可以随时抛出来

**Comment by cjinhuo** [comment]
你试着卸载，再重新安装看看行不行

**Comment by liuhuapiaoyuan** [comment]
https://github.com/cjinhuo/blazwitcher/pull/32

已经提交PR，求合并 万分感谢

**Comment by cjinhuo** [comment]
<img width="488" alt="image" src="https://github.com/user-attachments/assets/e4c41862-d955-483d-854b-fc45ee21837c">
已上线
